// Generated by IB v0.2.6 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface Camera





-(IBAction) imagePickerControllerDidCancel:(id) picker;
-(IBAction) picker;
-(IBAction) dismiss;
-(IBAction) camera_device;
-(IBAction) media_type_to_symbol:(id) media_type;
-(IBAction) symbol_to_media_type:(id) symbol;
-(IBAction) error:(id) type;
-(IBAction) load_constants_hack;

@end


@interface ParserError: StandardError







@end


@interface NSNotificationCenter





-(IBAction) observers;
-(IBAction) unobserve:(id) observer;

@end


@interface NSURLRequest





-(IBAction) to_s;

@end


@interface UIView





-(IBAction) handle_gesture:(id) recognizer;

@end


@interface UIViewController





-(IBAction) content_frame;

@end


@interface Response





-(IBAction) update:(id) values;
-(IBAction) to_s;
-(IBAction) update_status_description;

@end


@interface Query





-(IBAction) to_s;
-(IBAction) connectionDidFinishLoading:(id) connection;
-(IBAction) create_request;
-(IBAction) set_content_type;
-(IBAction) create_request_body;
-(IBAction) append_payload:(id) body;
-(IBAction) append_form_params:(id) body;
-(IBAction) append_files:(id) body;
-(IBAction) append_body_boundary:(id) body;
-(IBAction) create_url:(id) url_string;
-(IBAction) validate_url:(id) url;
-(IBAction) escape:(id) string;
-(IBAction) convert_payload_to_url;
-(IBAction) log:(id) message;
-(IBAction) escape_line_feeds:(id) hash;
-(IBAction) patch_nsurl_request:(id) request;
-(IBAction) call_delegator_with_response;

@end


@interface InvalidURLError: StandardError







@end


@interface InvalidFileError: StandardError







@end


@interface PeriodicTimer





-(IBAction) cancel;

@end


@interface Queue





-(IBAction) initialize;
-(IBAction) size;

@end


@interface Timer





-(IBAction) cancel;

@end


@interface RSSParser





-(IBAction) initialize;
-(IBAction) to_hash;

@end


@interface RSSItem





-(IBAction) initialize;
-(IBAction) to_hash;
-(IBAction) parserDidStartDocument:(id) parser;
-(IBAction) parserDidEndDocument:(id) parser;
-(IBAction) parserError;

@end


@interface InvalidPlayerType: StandardError







@end


@interface NilPlayerCallback: StandardError







@end


@interface Player





-(IBAction) stop;
-(IBAction) media_player;
-(IBAction) set_player_options:(id) options;

@end


@interface CLLocationCoordinate2D





-(IBAction) distance_to:(id) cl_location_2d;

@end


@interface SugarNotFoundException: Exception







@end


@interface Fixnum





-(IBAction) nth;
-(IBAction) ordinalize;
-(IBAction) before:(id) date;
-(IBAction) ago;
-(IBAction) after:(id) date;
-(IBAction) hence;

@end


@interface NSArray





-(IBAction) to_pointer:(id) type;
-(IBAction) nsindexpath;
-(IBAction) nsindexset;

@end


@interface NSCoder





-(IBAction) bool:(id) key;
-(IBAction) double:(id) key;
-(IBAction) float:(id) key;
-(IBAction) int:(id) key;
-(IBAction) point:(id) key;
-(IBAction) rect:(id) key;
-(IBAction) size:(id) key;

@end


@interface NSDate





-(IBAction) string_with_style:(id) style;
-(IBAction) string_with_format:(id) format;
-(IBAction) timezone;
-(IBAction) era;
-(IBAction) utc_offset;
-(IBAction) date_array;
-(IBAction) time_array;
-(IBAction) datetime_array;
-(IBAction) start_of_day;
-(IBAction) end_of_day;
-(IBAction) start_of_month;
-(IBAction) end_of_month;
-(IBAction) days_in_month;
-(IBAction) days_in_year;

@end


@interface NSIndexPath





-(IBAction) to_a;

@end


@interface IndexPath





-(IBAction) initialize:(id) values;

@end


@interface NSIndexSet





-(IBAction) to_a;

@end


@interface NSString





-(IBAction) nsurl;
-(IBAction) uiimage;
-(IBAction) uiimageview;
-(IBAction) escape_url;
-(IBAction) unescape_url;

@end


@interface NSString





-(IBAction) document;
-(IBAction) resource;
-(IBAction) resource_url;
-(IBAction) info_plist;

@end


@interface NSURL





-(IBAction) open;

@end


@interface NSUserDefaults





-(IBAction) remove:(id) key;

@end


@interface Object





-(IBAction) to_nsuserdefaults;

@end


@interface NilClass





-(IBAction) to_nsuserdefaults;

@end


@interface NSArray





-(IBAction) to_nsuserdefaults;

@end


@interface NSDictionary





-(IBAction) to_nsuserdefaults;

@end


@interface Numeric





-(IBAction) percent;
-(IBAction) radians;
-(IBAction) degrees;
-(IBAction) pi;
-(IBAction) meters;
-(IBAction) in_meters;
-(IBAction) kilometers;
-(IBAction) in_kilometers;
-(IBAction) miles;
-(IBAction) in_miles;
-(IBAction) feet;
-(IBAction) in_feet;
-(IBAction) bytes;
-(IBAction) kilobytes;
-(IBAction) megabytes;
-(IBAction) gigabytes;
-(IBAction) terabytes;
-(IBAction) petabytes;
-(IBAction) exabytes;

@end


@interface Symbol





-(IBAction) look_in:(id) here;
-(IBAction) uidevice;
-(IBAction) uideviceorientation;
-(IBAction) uiinterfaceorientation;
-(IBAction) uiinterfacemask;
-(IBAction) uitextalignment;
-(IBAction) uilinebreakmode;
-(IBAction) uibaselineadjustment;
-(IBAction) uibuttontype;
-(IBAction) uibordertype;
-(IBAction) uicontrolstate;
-(IBAction) uicontrolevent;
-(IBAction) uireturnkey;
-(IBAction) uiactivityindicatorstyle;
-(IBAction) uisegmentedstyle;
-(IBAction) uidatepickermode;
-(IBAction) uicontentmode;
-(IBAction) uitablestyle;
-(IBAction) uitablerowanimation;
-(IBAction) uitablecellstyle;
-(IBAction) uitablecellaccessory;
-(IBAction) uitablecellselectionstyle;
-(IBAction) uitablecellseparatorstyle;
-(IBAction) uistatusbarstyle;
-(IBAction) uibarmetrics;
-(IBAction) uibarbuttonitem;
-(IBAction) uikeyboardtype;
-(IBAction) uiautoresizemask;
-(IBAction) uiimagesource;
-(IBAction) uiimagecapture;
-(IBAction) uiimagecamera;
-(IBAction) uiimagequality;
-(IBAction) catimingfunction;
-(IBAction) cglinecap;
-(IBAction) cglinejoin;
-(IBAction) uigesturerecognizerstate;
-(IBAction) uifontsize;
-(IBAction) nsdatestyle;
-(IBAction) nsnumberstyle;

@end


@interface Numeric





-(IBAction) milliseconds;
-(IBAction) seconds;
-(IBAction) minutes;
-(IBAction) hours;
-(IBAction) days;
-(IBAction) weeks;
-(IBAction) months;
-(IBAction) years;

@end


@interface NSError





-(IBAction) localized;
-(IBAction) to_s;

@end


@interface NSLayoutConstraint





-(IBAction) to_s;

@end


@interface NSSet





-(IBAction) to_s;

@end


@interface UIColor





-(IBAction) to_s;

@end


@interface UIEvent





-(IBAction) to_s;

@end


@interface UITouch





-(IBAction) to_s;

@end


@interface UIViewController





-(IBAction) to_s;

@end


@interface UIActionSheet





-(IBAction) dummy;

@end


@interface UIActivityIndicatorView





-(IBAction) large;
-(IBAction) white;
-(IBAction) gray;

@end


@interface UIAlertView





-(IBAction) dummy;

@end


@interface UIButton





-(IBAction) custom;
-(IBAction) rounded;
-(IBAction) rounded_rect;
-(IBAction) detail;
-(IBAction) detail_disclosure;
-(IBAction) info;
-(IBAction) info_light;
-(IBAction) info_dark;
-(IBAction) contact;
-(IBAction) contact_add;

@end


@interface UIColor





-(IBAction) cgcolor;
-(IBAction) red;
-(IBAction) green;
-(IBAction) blue;
-(IBAction) alpha;
-(IBAction) css_name;

@end


@interface UIControl





-(IBAction) sugarcube_callbacks;

@end


@interface UIImage





-(IBAction) uiimageview;
-(IBAction) nsdata;
-(IBAction) in_rect:(id) rect;
-(IBAction) scale_to_fill:(id) new_size;
-(IBAction) scale_within:(id) new_size;
-(IBAction) scale_to:(id) new_size;
-(IBAction) rotate:(id) angle_or_direction;
-(IBAction) masked:(id) mask_image;
-(IBAction) color_at:(id) point;
-(IBAction) at_scale:(id) scale;

@end


@interface UISegmentedControl





-(IBAction) plain:(id) items;
-(IBAction) bordered:(id) items;
-(IBAction) bar:(id) items;
-(IBAction) bezeled:(id) items;

@end


@interface UITextView





-(IBAction) sugarcube_callbacks;

@end


@interface UIView





-(IBAction) first_responder;
-(IBAction) controller;
-(IBAction) unshift:(id) view;
-(IBAction) show;
-(IBAction) hide;
-(IBAction) uiimage;

@end


@interface UIViewController





-(IBAction) push:(id) view_controller;

@end


@interface UINavigationController





-(IBAction) push:(id) view_controller;

@end


@interface UITabBarController





-(IBAction) push:(id) view_controller;

@end


@interface AppDelegate





-(IBAction) load_vc:(id) identifier;
-(IBAction) switch_to_vc:(id) vc;

@end


@interface MessageListController: UIViewController

@property IBOutlet UITextView * messages_view;
@property IBOutlet UITextField * message;



-(IBAction) textFieldShouldReturn:(id) textField;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) load_messages;
-(IBAction) new_message:(id) sender;

@end


@interface WallListController: UIViewController

@property IBOutlet id wall_list_table;
@property IBOutlet UITextField * server;
@property IBOutlet UITextField * topic;



-(IBAction) textFieldShouldReturn:(id) textField;
-(IBAction) viewWillAppear:(id) animated;
-(IBAction) refresh:(id) sender;
-(IBAction) new_wall:(id) sender;
-(IBAction) refresh_walls;
-(IBAction) load_wall:(id) sender;

@end



